language: go
go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
sudo : false # uses new containerized infrastructure
go_import_path: github.com/maxbrunsfeld/counterfeiter
install: scripts/deps.sh
script: scripts/test.sh
